# Generated by Django 5.2.5 on 2025-08-28 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkAccomplishmentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_started', models.DateField()),
                ('date_completed', models.DateField(blank=True, null=True)),
                ('request_type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('requesting_office', models.CharField(max_length=255)),
                ('assigned_personnel', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=50)),
                ('rating', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='WorkReport',
        ),
    ]
