# Generated by Django 5.2.5 on 2025-09-11 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('unit', models.CharField(default='pcs', help_text='Unit of measurement (e.g., pcs, liters, meters, box, set)', max_length=50)),
                ('category', models.CharField(blank=True, help_text='Category (e.g., Electrical, Furniture, Tools, Cleaning)', max_length=100, null=True)),
                ('owned_by', models.CharField(choices=[('GSO', 'GSO'), ('Unit Head', 'Unit Head'), ('Personnel', 'Personnel')], default='GSO', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='materialusage',
            name='material',
        ),
        migrations.RemoveField(
            model_name='materialusage',
            name='service_request',
        ),
        migrations.DeleteModel(
            name='Material',
        ),
        migrations.DeleteModel(
            name='MaterialUsage',
        ),
    ]
