# Generated by Django 5.2.4 on 2025-09-16 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0002_servicerequest_assigned_personnel'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('In Progress', 'In Progress'), ('Done for Review', 'Done for Review'), ('Completed', 'Completed')], default='Pending', max_length=20),
        ),
    ]
