# Generated by Django 5.2.4 on 2025-09-18 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0003_servicerequest_completed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('In Progress', 'In Progress'), ('Done for Review', 'Done for Review'), ('Completed', 'Completed'), ('cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
