# Generated by Django 5.2.4 on 2025-09-18 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0004_alter_servicerequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='unit',
            field=models.CharField(choices=[('repair and maintenance', 'Repair and Maintenance'), ('utility', 'Utility'), ('electrical', 'Electrical'), ('motorpool', 'Motorpool')], max_length=50),
        ),
    ]
