# Generated by Django 5.2.4 on 2025-09-18 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0005_alter_servicerequest_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
