# Generated by Django 5.2.4 on 2025-09-18 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0006_servicerequest_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='contact_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
