# Generated by Django 5.2.4 on 2025-09-18 15:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0007_servicerequest_contact_number_servicerequest_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerequest',
            name='assigned_personnel',
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='assigned_personnel',
            field=models.ManyToManyField(blank=True, related_name='assigned_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
