# Generated by Django 5.2.4 on 2025-09-20 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventoryitem_remove_materialusage_material_and_more'),
        ('requests', '0008_remove_servicerequest_assigned_personnel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventoryitem')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requests.servicerequest')),
            ],
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='materials',
            field=models.ManyToManyField(blank=True, related_name='requests', through='requests.RequestMaterial', to='inventory.inventoryitem'),
        ),
    ]
