# Generated by Django 5.2.4 on 2025-09-16 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migration_tool', '0002_alter_datamigration_target_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datamigration',
            name='target_model',
            field=models.CharField(choices=[('inventory.InventoryItem', 'Inventory Items'), ('reports.WorkAccomplishmentReport', 'Work Accomplishment Reports'), ('requests.Request', 'Requests')], max_length=100),
        ),
    ]
