# Generated by Django 4.2.9 on 2025-09-06 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='unit',
            field=models.CharField(choices=[('admin', 'Admin'), ('maintenance', 'Maintenance'), ('electrical', 'Electrical'), ('utilities', 'Utilities'), ('motorpool', 'Motorpool')], default='unassigned', max_length=50),
        ),
    ]
