# Generated by Django 5.2.4 on 2025-09-08 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_status_alter_user_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='unit',
            field=models.CharField(choices=[('admin', 'Admin'), ('requestor', 'Requestor'), ('maintenance', 'Maintenance'), ('electrical', 'Electrical'), ('utilities', 'Utilities'), ('motorpool', 'Motorpool')], default='unassigned', max_length=50),
        ),
    ]
