# Generated by Django 5.2.4 on 2025-09-13 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_status_user_account_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='unit',
            field=models.CharField(choices=[('admin', 'Admin'), ('requestor', 'Requestor'), ('maintenance', 'Maintenance'), ('electrical', 'Electrical'), ('utility', 'Utility'), ('motorpool', 'Motorpool')], default='unassigned', max_length=50),
        ),
    ]
