# Generated by Django 5.2.4 on 2025-09-18 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='unit',
            field=models.CharField(choices=[('admin', 'Admin'), ('requestor', 'Requestor'), ('maintenance', 'Maintenance'), ('electrical', 'Electrical'), ('utility', 'Utility'), ('motorpool', 'Motorpool'), ('unassigned', 'Unassigned')], default='unassigned', max_length=50),
        ),
    ]
