# Generated by Django 5.2.4 on 2025-09-18 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_department_alter_user_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('gso', 'GSO Office'), ('unit_head', 'Unit Head'), ('personnel', 'Personnel'), ('requestor', 'Requestor')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='unit',
            field=models.CharField(choices=[('maintenance', 'Maintenance'), ('electrical', 'Electrical'), ('utility', 'Utility'), ('motorpool', 'Motorpool'), ('unassigned', 'Unassigned')], default='unassigned', max_length=50),
        ),
    ]
