# Generated by Django 5.2.4 on 2025-09-18 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_role_alter_user_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='unit',
            field=models.CharField(choices=[('maintenance', 'Maintenance'), ('electrical', 'Electrical'), ('utility', 'Utility'), ('motorpool', 'Motorpool')], default='unassigned', max_length=50),
        ),
    ]
