# Generated by Django 5.2.4 on 2025-09-18 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_user_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='unit',
            field=models.CharField(blank=True, choices=[('repair and maintenance', 'Repair and Maintenance'), ('electrical', 'Electrical'), ('utility', 'Utility'), ('motorpool', 'Motorpool')], max_length=50, null=True),
        ),
    ]
