# Generated by Django 5.2.5 on 2025-08-28 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migration_tool', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datamigration',
            name='target_model',
            field=models.CharField(choices=[('inventory.Item', 'Inventory Items'), ('reports.WorkAccomplishmentReport', 'Work Accomplishment Reports'), ('requests.Request', 'Requests')], max_length=100),
        ),
    ]
